import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import sharp from 'sharp';
import {createApp} from '../src/app.mjs';

test('enabled source can be browsed as folders and photos, with album discovery limited to selected depth',async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'studio-browser-'));
  const photoRoot=path.join(root,'photos');
  await mkdir(path.join(photoRoot,'Studio','Wedding','Ceremony'),{recursive:true});
  const jpg=await sharp({create:{width:32,height:24,channels:3,background:'#456789'}}).jpeg().toBuffer();
  await writeFile(path.join(photoRoot,'Studio','Wedding','Ceremony','photo.jpg'),jpg);
  const app=await createApp({photoRoot,dataDir:path.join(root,'data'),cacheDir:path.join(root,'cache'),adminPassword:'test-password-1234',origin:'http://localhost:3210',background:false,logger:false});
  t.after(async()=>{await app.close();await rm(root,{recursive:true,force:true});});
  const request=(method,url,payload,cookie)=>app.inject({method,url,payload,headers:{origin:'http://localhost:3210',...(cookie?{cookie}:{})}});
  const login=await request('POST','/api/admin/login',{password:'test-password-1234'});
  const cookie=login.headers['set-cookie'].split(';')[0];
  assert.equal((await request('GET','/api/admin/browse',undefined,cookie)).json().folders.length,0);
  const source=(await request('POST','/api/admin/sources',{relative_path:'Studio',label:'Studio'},cookie)).json();
  const base='@source/'+source.id;
  assert.deepEqual((await request('GET','/api/admin/browse',undefined,cookie)).json().folders.map(f=>f.name),['Studio']);
  assert.deepEqual((await request('GET',`/api/admin/browse?path=${encodeURIComponent(base)}`,undefined,cookie)).json().folders.map(f=>f.name),['Wedding']);
  const ceremony=(await request('GET',`/api/admin/browse?path=${encodeURIComponent(base+'/Wedding/Ceremony')}`,undefined,cookie)).json();
  assert.deepEqual(ceremony.files.map(f=>f.name),['photo.jpg']);
  const thumb=await request('GET',`/api/admin/browse/thumb?path=${encodeURIComponent(ceremony.files[0].path)}`,undefined,cookie);
  assert.equal(thumb.statusCode,200,thumb.body);
  assert.match(thumb.headers['content-type'],/image\/webp/);
  assert.equal((await request('GET',`/api/admin/browse?path=${encodeURIComponent(base+'/../private')}`,undefined,cookie)).statusCode,400);
  assert.equal((await request('PATCH',`/api/admin/sources/${source.id}/options`,{auto_scan:false,scan_depth:1},cookie)).statusCode,200);
  const discovery=await request('POST',`/api/admin/sources/${source.id}/discover`,{},cookie);
  assert.equal(discovery.statusCode,202,discovery.body);
  assert.equal(discovery.json().created,1);
  assert.equal((await request('GET','/api/admin/projects',undefined,cookie)).json()[0].root,'Studio/Wedding');
  await request('POST','/api/admin/sources',{relative_path:'Studio/Wedding',label:'Wedding'},cookie);
  assert.deepEqual((await request('GET','/api/admin/browse',undefined,cookie)).json().folders.map(f=>f.name),['Studio']);
  await request('PATCH',`/api/admin/sources/${source.id}/options`,{auto_scan:false,scan_depth:2},cookie);
  assert.equal((await request('POST',`/api/admin/sources/${source.id}/discover`,{},cookie)).json().created,0);
  assert.equal((await request('GET','/api/admin/projects',undefined,cookie)).json().length,1);
});
