import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,mkdir,writeFile,rm,readdir,symlink } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import sharp from 'sharp';
import {createApp} from '../src/app.mjs';
import {cleanRelative,safePath} from '../src/security.mjs';

test('path validation rejects traversal, absolute paths and Windows escapes',()=>{
  for(const p of ['../private','a/../b','/etc/passwd','C:/private','a\\b','a\0b'])assert.throws(()=>cleanRelative(p));
  assert.equal(cleanRelative('wedding/ceremony'),'wedding/ceremony');
});

test('end-to-end: scan, scope, proofing, previews, ZIP, revocation, missing sources',async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'proofing-test-'));
  const photoRoot=path.join(root,'photos');await mkdir(path.join(photoRoot,'event','01_Ceremony','nested'),{recursive:true});await mkdir(path.join(photoRoot,'event','02_Private'),{recursive:true});
  const jpg=await sharp({create:{width:120,height:80,channels:3,background:'#48715c'}}).jpeg().toBuffer();
  await writeFile(path.join(photoRoot,'event','01_Ceremony','IMG_001.jpg'),jpg);
  await writeFile(path.join(photoRoot,'event','01_Ceremony','nested','IMG_002.jpg'),jpg);
  await writeFile(path.join(photoRoot,'event','02_Private','PRIVATE.jpg'),jpg);
  const app=await createApp({photoRoot,dataDir:path.join(root,'data'),cacheDir:path.join(root,'cache'),adminPassword:'test-password-1234',origin:'http://localhost:3210',background:false,logger:false});
  t.after(async()=>{await app.close();await rm(root,{recursive:true,force:true});});
  const request=(method,url,payload,cookie)=>app.inject({method,url,payload,headers:{origin:'http://localhost:3210',...(cookie?{cookie}:{})}});
  const login=await request('POST','/api/admin/login',{password:'test-password-1234'});assert.equal(login.statusCode,200);
  const admin=login.headers['set-cookie'].split(';')[0];
  assert.equal((await app.inject({method:'POST',url:'/api/admin/projects',payload:{name:'X',root:'event'},headers:{cookie:admin,origin:'https://evil.example'}})).statusCode,403);
  assert.equal((await request('POST','/api/admin/sources',{relative_path:'event',label:'Ảnh studio'},admin)).statusCode,201);
  const created=await request('POST','/api/admin/projects',{name:'Tuấn & An',root:'event'},admin);assert.equal(created.statusCode,201,created.body);const pid=created.json().id;
  const assignment=await request('PATCH',`/api/admin/projects/${pid}`,{name:'Tuấn & An',cron:'',timezone:'Asia/Ho_Chi_Minh',editor:'Minh Editor',internal_note:'Ưu tiên chỉnh màu'},admin);assert.equal(assignment.statusCode,200,assignment.body);
  const assigned=(await request('GET','/api/admin/projects',undefined,admin)).json().find(project=>project.id===pid);assert.equal(assigned.editor,'Minh Editor');assert.equal(assigned.internal_note,'Ưu tiên chỉnh màu');
  await app.services.scanner.wait();await app.services.worker.drain();
  const db=app.services.db;
  assert.equal(db.get('SELECT count(*) AS n FROM photos WHERE missing=0').n,3);
  assert.equal(db.get("SELECT count(*) AS n FROM photos WHERE status='ready'").n,3);
  const folders=(await request('GET',`/api/admin/projects/${pid}/folders`,undefined,admin)).json();
  const folder=folders.find(f=>f.relative_path==='01_Ceremony');
  const share=(await request('POST',`/api/admin/projects/${pid}/links`,{label:'Bride',password:'2468',phone:'0901234567',folder_ids:[folder.id],downloads:true,originals:true},admin)).json();
  const token=share.url.split('/').pop();
  assert.equal((await request('POST',`/api/share/${token}/unlock`,{name:'An',password:'bad'})).statusCode,401);
  const unlocked=await request('POST',`/api/share/${token}/unlock`,{name:'An',password:'2468'});assert.equal(unlocked.statusCode,200,unlocked.body);
  const client=unlocked.headers['set-cookie'].split(';')[0];
  const portal=await request('POST','/api/access',{phone:'090 123 4567'});assert.equal(portal.statusCode,200,portal.body);assert.equal(portal.json().url,'/album');
  assert.equal((await request('POST','/api/access',{phone:'0900000000'})).statusCode,401);
  const gallery=(await request('GET',`/api/client/gallery?token=${token}`,undefined,client)).json();assert.equal(gallery.folders.length,2);
  const photos=(await request('GET','/api/client/photos',undefined,client)).json().photos;assert.equal(photos.length,2);
  const denied=db.get("SELECT id FROM photos WHERE filename='PRIVATE.jpg'").id;
  assert.equal((await request('GET',`/api/client/photos/${denied}/preview`,undefined,client)).statusCode,404);
  const image=await request('GET',`/api/client/photos/${photos[0].id}/preview`,undefined,client);assert.equal(image.statusCode,200);assert.match(image.headers['content-type'],/image\/webp/);
  assert.equal((await request('GET',`/api/client/photos/${photos[0].id}/preview`)).statusCode,401);
  const list=gallery.lists[0].id;
  const set=(value)=>request('PUT',`/api/client/lists/${list}/photos/${photos[0].id}`,{selected:value},client);
  assert.equal((await set(true)).statusCode,200);await set(true);assert.equal(db.get('SELECT count(*) AS n FROM client_selections').n,1);
  const foreign=await request('POST',`/api/share/${token}/unlock`,{name:'Other',password:'2468'});const other=foreign.headers['set-cookie'].split(';')[0];
  // A link identifies one album customer; selections persist across new login sessions.
  assert.equal((await request('GET',`/api/client/lists/${list}/export`,undefined,other)).statusCode,200);
  await request('POST',`/api/client/lists/${list}/submit`,{submitted:true},client);assert.equal((await set(false)).statusCode,409);
  await request('POST',`/api/client/lists/${list}/submit`,{submitted:false},client);assert.equal((await set(false)).statusCode,200);await set(true);
  const exported=(await request('GET',`/api/client/lists/${list}/export`,undefined,client)).json();assert.match(exported.search_string,/IMG_00/);
  assert.equal((await request('POST',`/api/client/photos/${photos[0].id}/comments`,{x:1.2,y:0.3,body:'bad'},client)).statusCode,400);
  assert.equal((await request('POST',`/api/client/photos/${photos[0].id}/comments`,{x:0.25,y:0.5,body:'Làm sáng vùng mặt'},client)).statusCode,200);
  assert.equal((await request('GET',`/api/client/photos/${photos[0].id}/comments`,undefined,other)).json().length,1);
  const ticket=await request('POST','/api/client/downloads',{list_id:list,original:true},client);assert.equal(ticket.statusCode,200,ticket.body);
  const zip=await request('GET',ticket.json().url,undefined,client);assert.equal(zip.statusCode,200,zip.body.slice(0,100));assert.equal(zip.rawPayload.readUInt32LE(0),0x04034b50);assert.ok(zip.rawPayload.includes(jpg));assert.ok(!zip.rawPayload.includes(Buffer.from('PRIVATE.jpg')));assert.ok(zip.rawPayload.includes(Buffer.from('IMG_00')));
  assert.equal((await request('GET',ticket.json().url,undefined,client)).statusCode,404);
  assert.ok(!(await readdir(path.join(root,'cache'))).some(n=>n.endsWith('.zip')));
  const selectedTicket=await request('POST','/api/client/downloads',{photo_ids:[photos[1].id],original:false},client);assert.equal(selectedTicket.statusCode,200,selectedTicket.body);
  const selectedZip=await request('GET',selectedTicket.json().url,undefined,client);assert.equal(selectedZip.statusCode,200);assert.ok(selectedZip.rawPayload.includes(Buffer.from('IMG_002')));assert.ok(!selectedZip.rawPayload.includes(Buffer.from('IMG_001')));
  const revokeTicket=(await request('POST','/api/client/downloads',{original:false},client)).json();
  await request('POST',`/api/admin/links/${share.id}/revoke`,{},admin);
  assert.equal((await request('GET',revokeTicket.url,undefined,client)).statusCode,403);
  assert.equal((await request('GET',`/api/client/photos/${photos[0].id}/preview`,undefined,client)).statusCode,403);
  await rm(path.join(photoRoot,'event','01_Ceremony','IMG_001.jpg'));app.services.scanner.start(db.get('SELECT * FROM projects WHERE id=?',pid));await app.services.scanner.wait();
  assert.equal(db.get('SELECT count(*) AS n FROM photos WHERE missing=1').n,1);assert.equal(db.get('SELECT count(*) AS n FROM client_selections').n,1);
  await rm(path.join(photoRoot,'event'),{recursive:true,force:true});app.services.scanner.start(db.get('SELECT * FROM projects WHERE id=?',pid));await app.services.scanner.wait();
  assert.equal(db.get('SELECT count(*) AS n FROM photos WHERE missing=1').n,1);assert.equal(db.get('SELECT status FROM scan_runs ORDER BY rowid DESC LIMIT 1').status,'failed');
});
