import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm,readFile,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import {createApp} from '../src/app.mjs';
import {runMedia,supportedFile} from '../src/media.mjs';
import {cacheFile} from '../src/worker.mjs';
const bundledFfmpeg=path.resolve('.runtime/media-tools/node_modules/ffmpeg-static/ffmpeg.exe');
const ffmpeg=process.env.FFMPEG||(existsSync(bundledFfmpeg)?bundledFfmpeg:'ffmpeg');
test('media formats are recognized case-insensitively',()=>{for(const name of ['a.MOV','b.MXF','c.GIF','d.HEIF','e.NRW','f.BMP','g.PSD','h.JP2','i.RMVB'])assert.ok(supportedFile(name));assert.equal(supportedFile('a.txt'),false);});
test('mixed media: scan, video encoding, authorized range playback and ZIP',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'proof-media-'));
 const photoRoot=path.join(root,'photos');await mkdir(path.join(photoRoot,'event'),{recursive:true});
 let app; t.after(async()=>{await app?.close();await rm(root,{recursive:true,force:true});});
 await runMedia(ffmpeg,['-y','-f','lavfi','-i','color=c=green:s=160x120:d=1','-c:v','libx264',path.join(photoRoot,'event','clip.MOV')]);
 await runMedia(ffmpeg,['-y','-f','lavfi','-i','color=c=blue:s=80x60:d=1','-frames:v','1',path.join(photoRoot,'event','legacy.BMP')]);
 await sharp({create:{width:50,height:50,channels:3,background:'red'}}).gif().toFile(path.join(photoRoot,'event','sample.gif'));
 app=await createApp({photoRoot,dataDir:path.join(root,'data'),cacheDir:path.join(root,'cache'),ffmpeg,adminPassword:'test-password-1234',background:false,logger:false});
 const req=(method,url,payload,cookie,extra={})=>app.inject({method,url,payload,headers:{origin:'http://localhost:3210',...(cookie?{cookie}:{}),...extra}});
 const admin=(await req('POST','/api/admin/login',{password:'test-password-1234'})).headers['set-cookie'].split(';')[0];
 await req('POST','/api/admin/sources',{relative_path:'event',label:'Media'},admin);
 const created=await req('POST','/api/admin/projects',{name:'Mixed',root:'event'},admin);assert.equal(created.statusCode,201,created.body);const pid=created.json().id;
 await app.services.scanner.wait();await app.services.worker.drain();
 const rows=app.services.db.all('SELECT * FROM photos');assert.equal(rows.length,3);assert.ok(rows.every(p=>p.status==='ready'),JSON.stringify(rows));
 const video=rows.find(p=>p.extension==='.mov');const bytes=await readFile(cacheFile(app.services.config,video,'video'));
 const share=(await req('POST',`/api/admin/projects/${pid}/links`,{label:'Client',downloads:true,originals:false},admin)).json();
 const token=share.url.split('/').pop();const unlocked=await req('POST',`/api/share/${token}/unlock`,{name:'Test',password:''});const client=unlocked.headers['set-cookie'].split(';')[0];
 assert.equal((await req('GET',`/api/client/photos/${video.id}/video`)).statusCode,401);
 const partial=await req('GET',`/api/client/photos/${video.id}/video`,undefined,client,{range:'bytes=0-99'});assert.equal(partial.statusCode,206);assert.deepEqual(partial.rawPayload,bytes.subarray(0,100));
 assert.equal((await req('GET',`/api/client/photos/${video.id}/video`,undefined,client,{range:'bytes=999999999-'})).statusCode,416);
 const ticket=await req('POST','/api/client/downloads',{original:false},client);assert.equal(ticket.statusCode,200,ticket.body);
 const zip=await req('GET',ticket.json().url,undefined,client);assert.equal(zip.statusCode,200);assert.ok(zip.rawPayload.includes(Buffer.from('.mp4')));assert.ok(zip.rawPayload.includes(Buffer.from('.webp')));
 assert.equal((await req('POST','/api/client/downloads',{original:true},client)).statusCode,403);
 app.services.db.run('UPDATE links SET revoked=1 WHERE project_id=?',pid);
 assert.equal((await req('GET',`/api/client/photos/${video.id}/video`,undefined,client)).statusCode,403);
});
