import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createApp} from '../src/app.mjs';

test('first run creates exactly one administrator and signs it in',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'proofing-setup-'));await mkdir(path.join(root,'photos'));
 const options={photoRoot:path.join(root,'photos'),dataDir:path.join(root,'data'),cacheDir:path.join(root,'cache'),adminPassword:'',origin:'http://localhost:3210',background:false,logger:false};
 const app=await createApp(options);
 t.after(async()=>{await app.close();await rm(root,{recursive:true,force:true});});
 const status=await app.inject({method:'GET',url:'/api/setup/status'});assert.deepEqual(status.json(),{required:true});
 const created=await app.inject({method:'POST',url:'/api/setup',headers:{origin:options.origin},payload:{username:'owner',name:'Chủ Studio',password:'strong-password-123'}});
 assert.equal(created.statusCode,201,created.body);
 const cookie=created.headers['set-cookie'].split(';')[0];
 const me=await app.inject({method:'GET',url:'/api/admin/me',headers:{cookie}});assert.equal(me.json().username,'owner');assert.equal(me.json().role,'admin');
 assert.deepEqual((await app.inject({method:'GET',url:'/api/setup/status'})).json(),{required:false});
 const second=await app.inject({method:'POST',url:'/api/setup',headers:{origin:options.origin},payload:{username:'other',name:'Other',password:'another-password-123'}});assert.equal(second.statusCode,409);
});

test('settings and staff: role enforcement, invalidation, persistence and password rotation',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'proofing-users-'));await mkdir(path.join(root,'photos'));
 const options={photoRoot:path.join(root,'photos'),dataDir:path.join(root,'data'),cacheDir:path.join(root,'cache'),adminPassword:'initial-admin-pass',origin:'http://localhost:3210',background:false,logger:false};
 let app=await createApp(options);
 t.after(async()=>{await app.close();await rm(root,{recursive:true,force:true});});
 const req=(method,url,payload,cookie)=>app.inject({method,url,payload,headers:{origin:options.origin,...(cookie?{cookie}:{})}});
 const login=async(username,password)=>{const r=await req('POST','/api/admin/login',{username,password});assert.equal(r.statusCode,200,r.body);return r.headers['set-cookie'].split(';')[0];};
 let admin=await login('admin',options.adminPassword);
 const me=(await req('GET','/api/admin/me',undefined,admin)).json();assert.equal(me.role,'admin');
 assert.equal((await req('GET','/api/admin/settings')).statusCode,401);
 const settings=(await req('GET','/api/admin/settings',undefined,admin)).json().settings;
 assert.equal((await req('PUT','/api/admin/settings',{...settings,maxDownloads:100},admin)).statusCode,400);
 assert.equal((await req('PUT','/api/admin/settings',{...settings,defaultTimezone:'Invalid'},admin)).statusCode,400);
 const saved={...settings,brand:'Test Studio',defaultDownloads:false,defaultOriginals:false,maxZipFiles:42,defaultCron:''};
 assert.equal((await req('PUT','/api/admin/settings',saved,admin)).statusCode,200);
 assert.equal((await req('GET','/api/config')).json().name,'Test Studio');
 assert.equal(app.services.config.maxZipFiles,42);
 const created=await req('POST','/api/admin/users',{username:'editor.one',name:'Editor One',password:'editor-password-1',role:'staff'},admin);assert.equal(created.statusCode,201,created.body);
 const uid=created.json().id;let staff=await login('editor.one','editor-password-1');
 assert.equal((await req('GET','/api/admin/projects',undefined,staff)).statusCode,200);
 for(const route of ['/api/admin/settings','/api/admin/users','/api/admin/audit'])assert.equal((await req('GET',route,undefined,staff)).statusCode,403);
 assert.equal((await req('PUT','/api/admin/settings',saved,staff)).statusCode,403);
 assert.equal((await req('POST','/api/admin/users',{username:'hacker',name:'X',password:'password-12345',role:'admin'},staff)).statusCode,403);
 const users=(await req('GET','/api/admin/users',undefined,admin)).json();assert.ok(users.every(u=>!('password_hash' in u)));
 assert.equal((await req('PATCH',`/api/admin/users/${me.id}`,{name:'Owner',role:'staff',disabled:false},admin)).statusCode,400);
 assert.equal((await req('PATCH',`/api/admin/users/${uid}`,{name:'Editor One',role:'staff',disabled:true},admin)).statusCode,200);
 assert.equal((await req('GET','/api/admin/projects',undefined,staff)).statusCode,401);
 assert.equal((await req('POST','/api/admin/login',{username:'editor.one',password:'editor-password-1'})).statusCode,401);
 await req('PATCH',`/api/admin/users/${uid}`,{name:'Editor One',role:'staff',disabled:false},admin);
 staff=await login('editor.one','editor-password-1');
 await req('POST',`/api/admin/users/${uid}/password`,{password:'editor-password-2'},admin);
 assert.equal((await req('GET','/api/admin/projects',undefined,staff)).statusCode,401);
 staff=await login('editor.one','editor-password-2');
 assert.equal((await req('POST','/api/admin/account/password',{currentPassword:'wrong',password:'editor-password-3'},staff)).statusCode,400);
 assert.equal((await req('POST','/api/admin/account/password',{currentPassword:'editor-password-2',password:'editor-password-3'},staff)).statusCode,200);
 const secondAdmin=await login('admin',options.adminPassword);
 assert.equal((await req('POST','/api/admin/account/password',{currentPassword:options.adminPassword,password:'changed-admin-pass'},admin)).statusCode,200);
 assert.equal((await req('GET','/api/admin/me',undefined,secondAdmin)).statusCode,401);
 await app.close();app=await createApp(options);
 admin=await login('admin','changed-admin-pass');
 assert.equal((await req('GET','/api/admin/settings',undefined,admin)).json().settings.brand,'Test Studio');
 assert.equal((await req('POST','/api/admin/login',{username:'admin',password:options.adminPassword})).statusCode,401);
 assert.ok((await req('GET','/api/admin/audit',undefined,admin)).json().length>=5);
});
