"use client";
import {useEffect,useState} from 'react';
import {api,json} from '@/lib/api';
export default function Console(){
 const [sources,setSources]=useState<any[]>([]),[path,setPath]=useState(''),[label,setLabel]=useState(''),[error,setError]=useState(''),[section,setSection]=useState('folders'),[selected,setSelected]=useState<any>(null),[search,setSearch]=useState('');
 const load=()=>api('/admin/sources').then(setSources).catch(e=>setError(e.message)); useEffect(()=>{void load()},[]);
 async function add(e:any){e.preventDefault();try{await api('/admin/sources',json('POST',{label:label||path.split('/').pop()||'Nguồn ảnh',relative_path:path}));setPath('');setLabel('');await load()}catch(e:any){setError(e.message)}}
 async function toggle(s:any){await api('/admin/sources/'+s.id,json('PATCH',{enabled:!s.enabled}));await load()}
 const nav=[['overview','Tổng quan'],['clients','Danh sách khách'],['log','Nhật ký'],['folders','Thư mục nguồn'],['advanced','Tính năng nâng cao'],['settings','Cài đặt']]; const rows=sources.filter(s=>(s.label+' '+s.relative_path).toLowerCase().includes(search.toLowerCase()));
 return <main className="console-shell"><aside className="console-sidebar"><div className="console-brand"><span className="console-brand-icon">S</span><strong>Studio Gallery<br/>Console</strong></div>{nav.map(([key,label])=><button key={key} className={section===key?'active':''} onClick={()=>setSection(key)}>{label}</button>)}</aside><section className="console-workspace"><header className="console-topbar"><div><div className="eyebrow">STUDIO GALLERY CONSOLE</div><h1>{section==='folders'?'Thư mục nguồn':'Studio Gallery'}</h1></div><input className="console-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="⌕  Tìm kiếm"/></header>{section==='folders'?<><div className="console-toolbar"><button disabled={!selected} onClick={()=>selected&&toggle(selected)}>Bật</button><button disabled={!selected} onClick={()=>selected&&toggle(selected)}>Tắt</button><button disabled={!selected}>Cài đặt</button><button>Khám phá phiên bản</button></div><div className="console-table"><div className="console-table-head"><span>Thư mục nguồn</span><span>Trạng thái</span><span>Số album</span><span>Giới hạn tải</span><span>Watermark</span><span>Khoá file</span></div>{rows.map(s=><div className={'console-table-row '+(selected?.id===s.id?'selected':'')} key={s.id} onClick={()=>setSelected(s)}><span><strong>{s.label}</strong><small>{s.relative_path}</small></span><span className={s.enabled?'status-on':'status-off'}>{s.enabled?'Đang bật':'Chưa bật'}</span><span>—</span><span>Tắt</span><span>Tắt</span><span>Tắt</span></div>)}{!rows.length&&<div className="console-empty">Chưa có thư mục nguồn. Hãy thêm share folder bên dưới.</div>}</div><section className="console-add"><h2>Thêm thư mục nguồn</h2><form onSubmit={add} className="console-form"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Tên thư mục, ví dụ Studio"/><input value={path} onChange={e=>setPath(e.target.value)} placeholder="/volume1/Studio" required/><button className="primary">Thêm thư mục</button></form></section></>:<div className="console-placeholder"><h2>{nav.find(n=>n[0]===section)?.[1]}</h2><p>Khu vực quản trị Studio Gallery. Chọn “Thư mục nguồn” để cấp quyền và bật quét thư mục.</p></div>}{error&&<p className="alert">{error}</p>}</section></main>
}
